export default {
  CANVAS_MOUSE_DOWN: 'CANVAS_MOUSE_DOWN',
  CANVAS_MOUSE_MOVE: 'CANVAS_MOUSE_MOVE',
  CANVAS_MOUSE_UP: 'CANVAS_MOUSE_UP',
  CHANGE_MODE: 'CHANGE_MODE',
  CHANGE_NODE_SHAPE: 'CHANGE_NODE_SHAPE',
  CHANGE_NODE_COLOR: 'CHANGE_NODE_COLOR',
  NODE_CLICK: 'NODE_CLICK',
  SET_GRID_REF: 'SET_GRID_REF',
  RESET: 'RESET',
};